**Problem:**
Given the following matrix A:

$A = \begin{pmatrix}
    1 & 2  \\
    2 & 4 \\ 
\end{pmatrix}$

is already singular. Find its $\lambda$'s and $x$'s

Problem from [Introduction to Linear Algebra, 5th Ed](https://math.mit.edu/~gs/linearalgebra/ila5/linearalgebra5_6-1.pdf)


In [27]:
import torch 

A = torch.Tensor([[1, 2], [2, 4]])

A


tensor([[1., 2.],
        [2., 4.]])

$A = \begin{pmatrix} 
a & b \\
c & d 
\end{pmatrix}$

$\det(A - \lambda I) = \det{ \begin{pmatrix} a - \lambda & b \\ c & d - \lambda \end{pmatrix}}$

$ = \lambda^2 - (a + d)\lambda + (ad - bc)$

$\lambda^2 - (a + d)\lambda = 0$

$\lambda(\lambda - (a + d)) = 0$

$${\lambda}_1 = 0$$
$${\lambda}_2 = a + d$$

In [29]:
l1 = 0.0 # Since the matrix is singular, we know that one eigenvalue must be 0
l2 = A.trace() #take the sum of diagnal
sol = torch.Tensor([0.0, l2])
sol

tensor([0., 5.])

**[QR Decomposition](https://en.wikipedia.org/wiki/QR_decomposition)**

In [31]:
n  = A.size(0)
Q = torch.rand(n, n)


Q, R = torch.linalg.qr(A, mode="complete")

sol = torch.diag(R)

sol



tensor([-2.2361e+00, -1.0834e-08])

In [32]:
eigvals = torch.linalg.eigvals(A)
eigvals

tensor([0.+0.j, 5.+0.j])